name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.zz08s.mongodb.net
      MONGODB_USERNAME: mohamedessam
      MONGODB_PASSWORD: iw1dJSH8om19mFAk
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Start server in the background
        run: |
          # Start the server in the background and log output
          npm start > server.log 2>&1 &
          SERVER_PID=$!
          echo "Server started with PID $SERVER_PID"
          
          # Wait for the server to respond using curl (timeout after 2 minutes)
          for i in {1..24}; do
            curl -s http://127.0.0.1:${PORT} && break
            echo "Waiting for server..."
            sleep 5
          done || {
            echo "Server did not respond in time; displaying logs:"
            cat server.log
            exit 1
          }
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
