name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.zz08s.mongodb.net
      MONGODB_USERNAME: mohamedessam
      MONGODB_PASSWORD: iw1dJSH8om19mFAk
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Start server in the background
        run: |
          # Start the server in the background
          npm start > server.log 2>&1 &
          SERVER_PID=$!
          echo "Server started with PID $SERVER_PID"

          # Wait up to 2 minutes for the server to start
          npx wait-on http://127.0.0.1:${PORT} --timeout 120000 || {
            echo "Server failed to start on time; displaying logs:"
            cat server.log
            exit 1
          }
          
          # Check if the server is responding
          echo "Checking server status with curl:"
          curl -I http://127.0.0.1:${PORT} || {
            echo "Server is not responding to curl; displaying logs:"
            cat server.log
            exit 1
          }
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
      - name: Stop server
        if: success()
        run: kill $SERVER_PID
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
